# Test: braid-module-no-discard
#
# Intent:
#   Assert at eval time that no LUKS device generated by the braid module has
#   `allowDiscards` enabled.
#
# Why it exists:
#   storage.nix currently omits `allowDiscards` (defaulting to false), which
#   is correct: enabling discards on LUKS leaks metadata about which sectors
#   are in use, compromising full-disk encryption guarantees. This eval-time
#   test is the cheapest regression guard — it catches any future commit that
#   silently enables it without requiring a VM boot.
#
# Scenario:
#   A developer adds `allowDiscards = true;` to improve SSD performance without
#   realising the security trade-off. This derivation fails at build time,
#   blocking the change before it reaches CI.
{ nixpkgs, system }:
let
  pkgs = nixpkgs.legacyPackages.${system};
  lib = pkgs.lib;

  evaluated = (nixpkgs.lib.nixosSystem {
    inherit system;
    modules = [
      ../../modules/braid
      {
        braid.enable = true;
        braid.disks.disk1.byId = "/dev/disk/by-id/virtio-disk1";
        braid.disks.disk2.byId = "/dev/disk/by-id/virtio-disk2";
        # Minimal NixOS config to satisfy module evaluation
        boot.loader.grub.enable = false;
        fileSystems."/".device = "tmpfs";
        fileSystems."/".fsType = "tmpfs";
        system.stateVersion = "25.11";
      }
    ];
  }).config;

  luksDevices = evaluated.boot.initrd.luks.devices;

  discardEnabled = builtins.filter
    (name: luksDevices.${name}.allowDiscards)
    (builtins.attrNames luksDevices);

in pkgs.runCommand "braid-module-no-discard" {} ''
  ${if discardEnabled != []
    then ''echo "FAIL: allowDiscards enabled on: ${toString discardEnabled}" && exit 1''
    else ''echo "PASS: no LUKS device has allowDiscards enabled"''}
  touch $out
''
